title: Developer Melange
email: david@leitner.io
description: >-
  A monthly podcast which brings you regular discussions about software engineering topics. 
  All of them, in one way or another, related to building great software products.
url: https://developermelange.github.io
twitter_username: devmelange
github_username: developermelange

permalink: /:title/
future: true

hosts:
  - name: David Leitner
    twitter: duffleit
  - name: Christian Haas
    twitter: dertseha
  - name: Peter Kofler
    twitter: codecopkofler

  # Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
