title: Developer Melange
email: david@leitner.io
description: >- 
  A podcast for developers interested in building great software products. 
  Every episode brings you regular discussions about topics related to 
  software craftmanship.
url: developermelange.github.io
twitter_username: devmelange
github_username:  developermelange

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
