name: Jekyll CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build it
        run: |
          bundle exec jekyll doctor
          bundle exec jekyll build
      - name: Keep site files
        uses: actions/upload-artifact@v2
        with:
          name: Generated_Jekyll_Site
          path: ./_site
